//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap lightbulb {
            get {
                object obj = ResourceManager.GetObject("lightbulb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ///////////////
        ////// Variables ///
        //////////////////
        ///
        ///float4x4 projMat;			// Project Matrix.
        ///float4x4 viewMat;			// View Matrix.
        ///float4x4 worldMat;		// World Matrix.
        ///float4x4 lightWVP;		// Light World View Projection Matrix.
        ///float4 lightPos[3];		// Position of the lights.
        ///float4 eyePos;				// Position of the camera.
        ///
        ///texture ambientMap;
        ///texture diffuseMap;	
        ///texture specularMap;	
        ///texture normalMap;
        ///
        ///texture glowMap;
        ///texture renderedScene;
        ///texture shadowMapLight1;
        ///texture shadowMapLight2;
        ///tex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shader {
            get {
                return ResourceManager.GetString("Shader", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap You_can_t_sell_yourself_for_a_buck__junior_ {
            get {
                object obj = ResourceManager.GetObject("You can\'t sell yourself for a buck, junior.", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
